<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzurePlayground.Application\AzurePlayground.Application.csproj" />
    <ProjectReference Include="..\AzurePlayground.Domain\AzurePlayground.Domain.csproj" />
    <ProjectReference Include="..\AzurePlayground.Infra.Data\AzurePlayground.Infra.Data.csproj" />
  </ItemGroup>

</Project>
